### ISSUE TITLE
For the pretrained models 

### ISSUE THREAD

**Issue by z050209** [anindita127/IMoS#11]
hi, I have some questions regarding test_synthesis.py code model loading part:
1. I noticed there is a given model GNet, and it was not mentioned in the paper, may I know how this was used? 
https://github.com/anindita127/IMoS/blob/main/src/consts/GNet_model.pt

2. for the pretrained model of action recognition - the exp_121_model_CVAE_object_nojoint_lr_0-0005_batchsize_1_ 
I have also try to train this model using  https://github.com/anindita127/IMoS/blob/main/src/train/train_action_recognition.py
But this model was not loaded in the test_synthesis.py, in this case, how to use this model?

Thanks.

**Comment by anindita127** [comment]
Hi. Thanks for your interest in our work. 

1. We did mention the GNet initialization in our paper. Please refer to the last few lines of Section 3.2.4. Also in test_synthesis.py please follow these lines to initialize with GNet. https://github.com/anindita127/IMoS/blob/main/src%2Ftest%2Ftest_synthesis.py#L404

2. The action classifier is needed for the evaluation so it is loaded in eval.py

Hope this helps!

**Comment by z050209** [comment]
Thanks and noted.

For the GNet initialization, noted it is from GOAL to predict the human object grasp pose. Just to check if my understanding is right: In the normal grab dataset test, it was commented out as the test dataset is already processed with the intial human contact pose, only if the person initially is not holding the object, then need to uncomment the GNet initialization part right?

Thanks.

**Comment by z050209** [comment]
Sorry, I have one more queries, I tried the training pipeline and retrained body and arm model. use the test_synthesis.py and the render_smplx.py to visualize the result, however, even if I uncomment out the 7 lines mentioned in test_synthesis.py, the result is not as good as your pretrained model. The result shows the person is moving object but not in a reasonable manner, seems just randomly moving around. May I know is there any other part that I need to take note on, or any special configuration to improve this? In my training, I used the default set up without any change. 

Thank you and look forward for your reply.

**Comment by anindita127** [comment]
Hello,

To answer the first question: yes you use the GNet optimization when you do not know the initial grasp contact points.

To answer the second question: we do not have any separate code for training apart from the one already posted. We also mentioned the main configurations/hyper parameters needed in our argUtils code. One suggestion can be to initialize with our pretrained arm model weights and retrain from there. 
Hope this helps!

**Comment by z050209** [comment]
Thanks for the answers, I have retrained for a few  times with your default setup, the arms are still looks different from the result produced by your pretrained model.. not sure if there is any other thing can be modified, besides comment out the following lines,  I tried to reorder the dimension sequence in other sequence in test_sythesis.py also but didn't find the optimal one   

 arms_rot_body_in[..., 0, :] = arms_rot_out[..., 3, :]
 arms_rot_body_in[..., 1, :] = arms_rot_out[..., 0, :]
 arms_rot_body_in[..., 2, :] = arms_rot_out[..., 4, :]
 arms_rot_body_in[..., 3, :] = arms_rot_out[..., 1, :]
 arms_rot_body_in[..., 4, :] = arms_rot_out[..., 5, :]
 arms_rot_body_in[..., 5, :] = arms_rot_out[..., 2, :]

Also for the trajectory of the object, I noticed that before optimization, the object pose is the same even if using different models, it is given as is in the GRABnet  but not predicted right?

**Comment by z050209** [comment]
Also, just curious, why there is a mismatch in the joint ordering in the pre-trained model and how did you find out the correct sequence. Thanks 

'''Do the following rearrangement if you use the pre-trained model. There is a mismatch in the joint ordering in the pre-trained weights.'''
                '''Comment out the next 7 lines if you train your own model'''
arms_rot_body_in[..., 0, :] = arms_rot_out[..., 3, :]
arms_rot_body_in[..., 1, :] = arms_rot_out[..., 0, :]
arms_rot_body_in[..., 2, :] = arms_rot_out[..., 4, :]
arms_rot_body_in[..., 3, :] = arms_rot_out[..., 1, :]
arms_rot_body_in[..., 4, :] = arms_rot_out[..., 5, :]
arms_rot_body_in[..., 5, :] = arms_rot_out[..., 2, :]

**Comment by anindita127** [comment]
Hi, when we initially started experiments, the arrangement of the arm joint indices was:
 arm_joints = [17, 19, 21, 16, 18, 20]
 (the right arm joint indices and the left arm joint indices were concatenated).

However, in our later experiments we modified the arrangement to arm_joints = [16, 17, 18, 19, 20, 21] ((https://github.com/anindita127/IMoS/blob/cc84feb3ad4ac221d9927a1f07a6102bb91df460/src/train/train_arms.py#L29)).

The best pre-trained weights for the arm model were from one of our old experiments so we had to use that rearrangement (https://github.com/anindita127/IMoS/blob/cc84feb3ad4ac221d9927a1f07a6102bb91df460/src/test/test_synthesis.py#L384) to get the correct sequence on which the model was trained.

If you want to use our pre-trained model weights as an initialization, please rearrange the pre-trained weights for arm joint to [16, 17, 18, 19, 20, 21] sequence first.

**Comment by anindita127** [comment]
For the other question regarding the trajectory of the object:
For the optimization, the object needs to be at rest and in an upright position, and we have used the ground-truth object position as our initial object position before the optimization.
