### ISSUE TITLE
pyglet.gl.ContextException: Could not create GL context

### ISSUE THREAD

**Issue by 223d** [anindita127/IMoS#6]
Hi 
When I ran  python src/visualize/render_smplx.py，this problem occurred. 
May I ask what is the reason for this?  
the version of Opengl to be 3.3?

@anindita127 

Looking forward to your reply!

**Comment by 223d** [comment]
I have another question, what is the pyglet version corresponding to opengl version 3.1.0?

**Comment by anindita127** [comment]
Hi, the pyglet version I have used is 1.5.27
